# ==========================================
# Supabase Local Development Configuration
# For ZERO-CHAOS testing and OAuth setup
# ==========================================

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website (for OAuth redirects)
site_url = "http://localhost:3000"

# A list of *exact* URLs that auth providers are permitted to redirect to post authentication
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/api/auth/callback",
  "https://prismy.in/auth/callback",
  "https://prismy.in/api/auth/callback"
]

# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600

# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# ==========================================
# OAUTH PROVIDERS FOR LOCAL DEVELOPMENT
# ==========================================

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
# Redirect URL for local development
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.external.github]
enabled = false
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_CLIENT_SECRET)"

[auth.external.apple]
enabled = false
client_id = "env(APPLE_CLIENT_ID)"
secret = "env(APPLE_CLIENT_SECRET)"

# ==========================================
# EDGE FUNCTIONS
# ==========================================
[functions]
verify_jwt = false

[analytics]
enabled = false