version: 2
snapshot:
  widths:
    - 1280
    - 768
    - 375
  percyCSS: |
    .sb-show-main { padding: 0 !important; }
    .sb-main-padded { padding: 0 !important; }
discovery:
  allowed-hostnames:
    - localhost
  request-headers:
    User-Agent: Percy/1.0 (Storybook)
storybook:
  include:
    - "**/*.stories.*"
  exclude:
    - "**/*.test.*"