# Percy Visual Testing Configuration
# PRISMY ZERO-CHAOS TEST & RELEASE PLAYBOOK - Visual Regression Testing
# Critical UI components must pass visual regression before merge

version: 2

discovery:
  # Network idle strategy for better consistency
  network-idle-timeout: 750
  disable-cache: true
  
static-snapshots:
  # Base URL for static snapshots
  base-url: http://localhost:3000
  
  # Snapshot configuration
  snapshot-files: '**/*.html'
  ignore-files: 
    - '**/node_modules/**'
    - '**/.next/**'
    - '**/coverage/**'
    - '**/reports/**'
    - '**/*.test.{js,jsx,ts,tsx}'
    - '**/*.spec.{js,jsx,ts,tsx}'

# Enhanced snapshot configuration for Zero-Chaos Testing
snapshot:
  # Percy CSS for consistent rendering and hiding dynamic content
  percy-css: |
    /* Hide dynamic timestamps and loading indicators */
    [data-testid="timestamp"],
    [data-testid="loading"],
    .animate-spin,
    .animate-pulse,
    .animate-bounce {
      visibility: hidden !important;
    }
    
    /* Hide user-specific content for consistent snapshots */
    [data-testid="user-avatar"],
    [data-testid="user-email"],
    [data-testid="user-name"] {
      visibility: hidden !important;
    }
    
    /* Hide dynamic counters and metrics */
    [data-testid="credits-count"],
    [data-testid="usage-count"],
    [data-testid="file-count"] {
      visibility: hidden !important;
    }
    
    /* Ensure consistent font rendering across environments */
    * {
      -webkit-font-smoothing: antialiased !important;
      -moz-osx-font-smoothing: grayscale !important;
      text-rendering: optimizeLegibility !important;
    }
    
    /* Disable flaky animations for consistent snapshots */
    .transition-all,
    .transition-colors,
    .transition-opacity,
    .transition-transform {
      transition: none !important;
    }
    
    /* Hide auth-dependent elements */
    [data-percy-hide] {
      visibility: hidden !important;
    }
  
  # Enable JavaScript for dynamic content rendering
  enable-javascript: true
  
  # Wait for layout stability
  enable-layout: true
  
  # Minimum height to capture full component
  min-height: 1024

# Comparison thresholds per Zero-Chaos requirements
options:
  # Strict threshold - even 1px difference should fail
  threshold: 0.01
  
  # Include only meaningful visual differences
  include-same-height: false
  
  # Freeze animations for consistent comparison
  freeze-animated-image: true

# Multi-locale visual testing with Zero-Chaos validation
agent:
  asset-discovery:
    # Capture fonts and assets
    network-idle-timeout: 750
    allowed-hostnames:
      - fonts.googleapis.com
      - fonts.gstatic.com
      - rsms.me
      - "*.supabase.co"
      - "*.vercel.app"

# Browser and viewport configurations
browsers:
  - name: chrome
    # Desktop viewports
    additional-snapshots:
      - name: Desktop Large
        width: 1920
        height: 1080
      - name: Desktop Medium  
        width: 1440
        height: 900
      - name: Desktop Small
        width: 1280
        height: 720
      # Tablet viewports
      - name: Tablet Landscape
        width: 1024
        height: 768
      - name: Tablet Portrait
        width: 768
        height: 1024
      # Mobile viewports
      - name: Mobile Large
        width: 414
        height: 896
      - name: Mobile iPhone 12
        width: 390
        height: 844
      - name: Mobile Medium
        width: 375
        height: 667
      - name: Mobile Small
        width: 320
        height: 568

# RTL language support
rtl-languages:
  - ar

# Locale-specific configurations
locales:
  en:
    name: "English"
    direction: ltr
    font-family: "Inter, -apple-system, sans-serif"
  vi:
    name: "Tiếng Việt" 
    direction: ltr
    font-family: "Inter, -apple-system, sans-serif"
  ja:
    name: "日本語"
    direction: ltr
    font-family: "Inter, 'Noto Sans JP', sans-serif"
  ar:
    name: "العربية"
    direction: rtl
    font-family: "Inter, 'Noto Sans Arabic', sans-serif"
  zh:
    name: "中文"
    direction: ltr
    font-family: "Inter, 'Noto Sans SC', sans-serif"