# 🩺 Local Auth Development Environment
# Complete OAuth testing setup with Supabase local instance

version: '3.8'

services:
  # Supabase Database
  supabase-db:
    image: supabase/postgres:15.1.0.147
    container_name: prismy-auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-super-secret-jwt-token-with-at-least-32-characters-long
      POSTGRES_HOST: localhost
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - auth-network

  # Supabase Studio (Database UI)
  supabase-studio:
    image: supabase/studio:20240101-ce42139
    container_name: prismy-auth-studio
    ports:
      - "3001:3000"
    environment:
      SUPABASE_URL: http://supabase-auth:8000
      STUDIO_PG_META_URL: http://supabase-meta:8080
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    depends_on:
      - supabase-db
    networks:
      - auth-network

  # Supabase Auth Server
  supabase-auth:
    image: supabase/gotrue:v2.132.3
    container_name: prismy-auth-server
    ports:
      - "9999:9999"
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://localhost:9999
      
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:your-super-secret-jwt-token-with-at-least-32-characters-long@supabase-db:5432/postgres?search_path=auth
      
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: "http://localhost:3000,http://localhost:3000/auth/callback,https://prismy-production-*.vercel.app"
      
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      
      # OAuth Providers (add your real credentials for testing)
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: true
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: your-google-oauth-client-id
      GOTRUE_EXTERNAL_GOOGLE_SECRET: your-google-oauth-client-secret
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: http://localhost:9999/callback
      
      # Email settings (optional for testing)
      GOTRUE_SMTP_HOST: smtp.gmail.com
      GOTRUE_SMTP_PORT: 587
      GOTRUE_SMTP_USER: ""
      GOTRUE_SMTP_PASS: ""
      GOTRUE_SMTP_ADMIN_EMAIL: admin@prismy.in
      
      # Rate limiting
      GOTRUE_RATE_LIMIT_HEADER: X-RateLimit-Limit
      GOTRUE_RATE_LIMIT_EMAIL_SENT: 3
      
      # Logging
      GOTRUE_LOG_LEVEL: debug
      
    depends_on:
      - supabase-db
    networks:
      - auth-network

  # Supabase REST API
  supabase-rest:
    image: postgrest/postgrest:v12.0.1
    container_name: prismy-auth-rest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:your-super-secret-jwt-token-with-at-least-32-characters-long@supabase-db:5432/postgres
      PGRST_DB_SCHEMAS: public,auth,storage
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      PGRST_DB_USE_LEGACY_GUCS: false
    depends_on:
      - supabase-db
    networks:
      - auth-network

  # Supabase Realtime
  supabase-realtime:
    image: supabase/realtime:v2.25.50
    container_name: prismy-auth-realtime
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: supabase-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: your-super-secret-jwt-token-with-at-least-32-characters-long
      DB_NAME: postgres
      DB_SSL: false
      
      API_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      FLY_ALLOC_ID: fly-alloc-id
      FLY_APP_NAME: realtime
      SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8en4CpDi
      ERL_AFLAGS: -proto_dist inet_tcp
      ENABLE_TAILSCALE: false
      
    depends_on:
      - supabase-db
    networks:
      - auth-network

  # HTTPS Proxy for testing custom domains
  nginx-ssl:
    image: nginx:alpine
    container_name: prismy-auth-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - supabase-auth
    networks:
      - auth-network

volumes:
  supabase-db-data:
    driver: local

networks:
  auth-network:
    driver: bridge