# ===============================================
# Blackbox Exporter Configuration
# Endpoint monitoring and health checks
# ===============================================

modules:
  # HTTP 2xx probe
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: true
      
  # HTTPS probe with SSL verification
  https_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      follow_redirects: true
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: true
      
  # API health check
  api_health:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]
      method: GET
      headers:
        Accept: application/json
      fail_if_body_not_matches_regexp:
        - '"status":\s*"healthy"'
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: true
      
  # TCP probe
  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: true
      
  # PostgreSQL probe
  postgres_probe:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^SSH-2.0-"
      tls: false
      preferred_ip_protocol: "ip4"
      
  # Redis probe
  redis_probe:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - send: "PING\r\n"
        - expect: "\\+PONG"
      tls: false
      preferred_ip_protocol: "ip4"
      
  # DNS probe
  dns_probe:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: true
      query_name: "prismy.com"
      query_type: "A"
      valid_rcodes:
        - NOERROR
        
  # SSL certificate expiry check
  ssl_expiry:
    prober: http
    timeout: 5s
    http:
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"