name: Visual Regression Testing

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Storybook
      run: npm run build-storybook
      
    - name: Run Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        buildScriptName: 'build-storybook'
        exitZeroOnChanges: true
        
    - name: Run Vietnamese UI Tests
      run: |
        npm run test:visual:vietnamese
        
    - name: Performance Tests
      run: |
        npm run lighthouse:ci
        
    - name: Generate UI Quality Report
      run: |
        npm run quality:ui-report
        
    - name: Upload Quality Reports
      uses: actions/upload-artifact@v3
      with:
        name: ui-quality-reports
        path: |
          reports/visual-regression/
          reports/performance/
          reports/ui-quality/