# ===============================================
# Grafana Data Source Provisioning Configuration
# Configure data sources automatically
# ===============================================

apiVersion: 1

# List of data sources to insert/update
datasources:
  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: "30s"
    editable: true
    
  # Loki for logs
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    jsonData:
      maxLines: 1000
    editable: true
    
  # Tempo for traces
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
    editable: true
    
  # CloudWatch for AWS metrics
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: default
      defaultRegion: us-east-1
      customMetricsNamespaces: "Prismy/Application"
    editable: true
    
  # PostgreSQL for business metrics
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: prismy
    user: prismy
    secureJsonData:
      password: "$POSTGRES_PASSWORD"
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: true